# Dockerfile to build custom image for ros melodic with nvidia support

FROM ubuntu:bionic-20200807

ARG DEBIAN_FRONTEND=noninteractive

# setup timezone
RUN echo 'Etc/UTC' > /etc/timezone && \
    ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
    apt-get update && \
    apt-get install -q -y --no-install-recommends tzdata && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get -y install sudo

# install packages
RUN apt-get update && apt-get install -q -y --no-install-recommends libboost-filesystem-dev \
    libboost-system-dev \
    libboost-thread-dev \
    terminator \
    vim \
    libjsoncpp-dev \
    gimp \
    vlc \
    jstest-gtk \
    openssh-server \
    lm-sensors \
    htop \
    tmux \
    xclip \
    nano \
    vim \
    dbus-x11 \
    python3-pip \
    python-pip \
    software-properties-common \
    curl \
    git \
    ca-certificates \
    apt-utils \
    apt-transport-https \
    dirmngr \
    gnupg2 \
    wget \
    usbutils \
    net-tools \
    libeigen3-dev \
    libcanberra-gtk-module \
    libcanberra-gtk3-module \
    zip \
    python-tk \

# Install sublime
RUN curl -fsSL https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
RUN sudo add-apt-repository "deb https://download.sublimetext.com/ apt/stable/"
RUN apt-get update && apt-get install -y --no-install-recommends sublime-text

# setup keys
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

# setup sources.list
RUN echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros1-latest.list

# setup environment
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

ENV ROS_DISTRO melodic

# install ros packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-melodic-desktop-full=1.4.1-0* \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential \
    python-rosdep \
    python-rosinstall \
    python-vcstools \
    && rm -rf /var/lib/apt/lists/*

RUN rosdep init && rosdep update --rosdistro $ROS_DISTRO
RUN apt-get update
RUN apt-get -y install -y python-rosinstall ros-melodic-qt-ros
RUN pip install -U catkin_tools

#-------------------------------------------------------------------------------------------------------------
# will copy in make_container.sh
# # Terminator Config
# RUN mkdir -p /root/.config/terminator/
# COPY docker/config/terminator_config /root/.config/terminator/config 

# # setup entrypoint
# COPY docker/config/bashrc /root/.bashrc
COPY docker/config/ros_entrypoint.sh /
ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]
SHELL ["/bin/bash", "-c"]
CMD /bin/bash -c "source ~/.bashrc"
